# Site settings
title: p-jo github
email: petter@p-jo.se
# description: "Activist & Web Consultant. Guiding progressive organisations in the digital world."
url: http://petterjoelson.com
twitter:
  username: p_jo
facebook:
  publisher: petter.joelson
logo: /public/logo.png
social:
  links:
    - "https://medium.com/@p_jo"
    - "https://twitter.com/p_jo"
    - "https://www.facebook.com/petter.joelson"
    - "https://github.com/p-jo"
    - "https://flipboard.com/@p_jo"
    - "https://www.linkedin.com/in/petterjoelson"
baseurl: ""

# Build settings
markdown: kramdown
# relative_permalinks: true
permalink: pretty

gems:
  - jekyll-seo-tag

# Get JSON-files
# jekyll_get:
#  - data: projects
#    json: 'https://secure.are.na/v2/channels/portfolio--14'
#    cache: true

# Multilingual settings
# See https://github.com/tristen/multilingual
# permalink: /:categories/:title
# languages:
#   - name: 'English'
#     key: 'en'
#   - name: 'Español'
#     key: 'es'

# Prose settings
# See https://github.com/prose/prose/wiki
prose:
  rooturl: '_posts'

# Settings
exclude:  [".sass-cache", "bower_components", "Rakefile"]
