# Site settings
title: Petter Joelson
email: petter@p-jo.se
description: "Activist & Web Consultant"
baseurl: ""
twitter_username: p_jo
github_username:  p-jo

# Build settings
markdown: kramdown
# relative_permalinks: true
permalink: pretty

# Get JSON-files
# jekyll_get:
#  - data: projects
#    json: 'https://secure.are.na/v2/channels/portfolio--14'
#    cache: true

# Multilingual settings
# See https://github.com/tristen/multilingual
# permalink: /:categories/:title
# languages:
#   - name: 'English'
#     key: 'en'
#   - name: 'Español'
#     key: 'es'

# Prose settings
# See https://github.com/prose/prose/wiki
prose:
  rooturl: '_posts'

# Settings
exclude:  [".sass-cache", "bower_components", "Rakefile"]
